name: Demo Workflow failed
on:
  workflow_dispatch: # Manually trigger the workflow
    inputs:
      a:
        description: 'Value A, please give a number'
        required: true
        type: string
      b:
        description: 'Value B, please give a number'
        required: true
        type: string

jobs:
    print-message:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Set up Python
          uses: actions/setup-python@v4
        - name: Execute Python script
          run: python script/divide.py ${{ inputs.a }} ${{ inputs.b }}
        - name: Run a one-line script
          run: echo Hello, world!
  # my-job:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Post to a Slack channel
  #       id: slack
  #       uses: slackapi/slack-github-action@v1.24.0
  #       with:
  #         # Slack channel id, channel name, or user id to post message.
  #         # See also: https://api.slack.com/methods/chat.postMessage#channels
  #         channel-id: 'C03U708L0QM'
  #         # For posting a rich message using Block Kit
  #         slack-message: "Test Message"
  #       env:
  #         SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}            